import {
  HiOutlineBolt,
  HiOutlineChatBubbleLeftRight,
  HiOutlineCheckBadge,
  HiOutlineCloud,
  HiOutlineCodeBracket,
  HiOutlineCog6Tooth,
  HiOutlineCommandLine,
  HiOutlineCpuChip,
  HiOutlineDevicePhoneMobile,
  HiOutlineFaceSmile,
  HiOutlineGlobeAlt,
  HiOutlineLightBulb,
  HiOutlineMegaphone,
  HiOutlinePaintBrush,
  HiOutlineRocketLaunch,
  HiOutlineServerStack,
  HiOutlineShieldCheck,
  HiOutlineSparkles,
  HiOutlineStar,
  HiOutlineTrophy,
  HiOutlineUserGroup,
  HiOutlineUsers,
  HiOutlineWindow,
} from "react-icons/hi2";

export const serviceIcons = {
  Code: HiOutlineCodeBracket,
  Smartphone: HiOutlineDevicePhoneMobile,
  Cpu: HiOutlineCpuChip,
  Terminal: HiOutlineCog6Tooth,
  Design: HiOutlinePaintBrush,
  Megaphone: HiOutlineMegaphone,
  Window: HiOutlineWindow,
  Server: HiOutlineServerStack,
  Cloud: HiOutlineCloud,
  Rocket: HiOutlineRocketLaunch,
  Users: HiOutlineUserGroup,
  Star: HiOutlineFaceSmile,
  Globe: HiOutlineGlobeAlt,
  Trophy: HiOutlineTrophy,
  Shield: HiOutlineShieldCheck,
  Bulb: HiOutlineLightBulb,
  Person: HiOutlineUsers,
  Spark: HiOutlineSparkles,
  Bolt: HiOutlineBolt,
  Chat: HiOutlineChatBubbleLeftRight,
  Badge: HiOutlineCheckBadge,
  Command: HiOutlineCommandLine,
};

export function getIcon(name) {
  return serviceIcons[name] || HiOutlineSparkles;
}
